name: Aggiungi Messaggio

on:
  repository_dispatch:
    types: [add-message]

jobs:
  update-messages:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configura Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Aggiungi nuovo messaggio
        env:
          TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          # Ottieni il contenuto corrente
          curl -H "Authorization: Bearer $TOKEN" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o messages.json \
               https://api.github.com/repos/Quasiamici/lavagna/contents/messages.json

          # Aggiungi il nuovo messaggio
          echo "Aggiungi messaggio: ${{ github.event.client_payload.message }}"
          echo $(jq ". + [\"${{ github.event.client_payload.message }}\"]" messages.json) > messages.json

          # Aggiorna il file su GitHub
          curl -X PUT \
               -H "Authorization: Bearer $TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"message\": \"Aggiunto nuovo messaggio\", \"content\": \"$(cat messages.json | base64 -w 0)\", \"sha\": \"$(curl -s -H \"Authorization: Bearer $TOKEN\" https://api.github.com/repos/Quasiamici/lavagna/contents/messages.json | jq -r '.sha')\"}" \
               https://api.github.com/repos/Quasiamici/lavagna/contents/messages.json
