name: Aggiungi Messaggio

on:
  push:
    branches:
      - main  # O il ramo che usi

jobs:
  update-messages:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}   # Usa il tuo token di accesso personalizzato

      # Configurazione di Git
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

      # Ottieni il contenuto corrente di messages.json
      - name: Visualizza messaggi correnti
        run: |
          curl -o messages.json https://raw.githubusercontent.com/Quasiamici/lavagna/main/messages.json
          cat messages.json  # Visualizza il contenuto corrente

      # Aggiungi un nuovo messaggio usando jq per formattare correttamente il JSON
      - name: Aggiungi un nuovo messaggio
        run: |
          # Se il file è vuoto, creiamo un array vuoto prima di aggiungere il messaggio
          if [ ! -s messages.json ]; then
            echo "[]" > messages.json
          fi
          
          # Aggiungi il nuovo messaggio all'array
          jq '. += [{"message": "Nuovo messaggio!"}]' messages.json > temp.json && mv temp.json messages.json
          
          # Visualizza il contenuto del file dopo la modifica
          cat messages.json

      # Commit e push delle modifiche
      - name: Commit e push delle modifiche
        run: |
          git add messages.json
          git commit -m "Aggiunto un nuovo messaggio"
          git push https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/Quasiamici/lavagna.git
