name: Aggiorna Messaggi

on:
  push:
    paths:
      - 'messages.json'

jobs:
  update_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Aggiornare messages.json
        run: |
          import json
          from datetime import datetime

          # Carica il file messages.json
          with open('messages.json', 'r') as f:
              messages = json.load(f)

          # Aggiungi un nuovo messaggio (senza duplicati)
          new_message = {
              "message": "Nuovo messaggio!",
              "date": datetime.now().isoformat()
          }
          if new_message not in messages:
              messages.append(new_message)

          # Scrivi il file aggiornato
          with open('messages.json', 'w') as f:
              json.dump(messages, f, indent=2)

      - name: Commit aggiornamenti
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add messages.json
          git commit -m "Aggiunto nuovo messaggio"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
