name: Update Messages JSON

on:
  push:
    paths:
      - 'messages.json'

jobs:
  update_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update messages.json
        run: |
          import json
          from datetime import datetime

          # Carica il file JSON
          with open('messages.json', 'r') as f:
              messages = json.load(f)

          # Aggiungi il nuovo messaggio
          new_message = {
              "message": "Nuovo messaggio aggiunto!",
              "date": datetime.now().isoformat()
          }
          messages.append(new_message)

          # Scrivi il file aggiornato
          with open('messages.json', 'w') as f:
              json.dump(messages, f, indent=2)

      - name: Commit updated messages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add messages.json
          git commit -m "Aggiunto un nuovo messaggio"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
