name: Aggiorna Messaggi

on:
  repository_dispatch:
    types: [add-message]

jobs:
  update-messages:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configura Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/Quasiamici/lavagna.git

      - name: Scarica messaggi
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o messages.json \
               https://api.github.com/repos/Quasiamici/lavagna/contents/messages.json

      - name: Aggiungi nuovo messaggio
        run: |
          echo '${{ github.event.client_payload.message }}' >> messages.json
          git add messages.json
          git commit -m "Aggiorna messaggi"
          git push
