name: Update Messages

on:
  push:
    paths:
      - 'messages.json'

jobs:
  update_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit messages update
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add messages.json
          git commit -m "Aggiunto un nuovo messaggio"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
