name: Update Pensieri
on:
  repository_dispatch:
    types: [update-pensieri]

jobs:
  update-pensieri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update pensieri.json
        run: |
          echo "${{ github.event.client_payload.pensiero }}" > nuovo_pensiero.txt
          jq ". + [\"$(cat nuovo_pensiero.txt)\"]" pensieri.json > pensieri_nuovo.json
          mv pensieri_nuovo.json pensieri.json

      - name: Commit and push changes
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add pensieri.json
          git commit -m "Aggiornato pensieri.json"
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }} HEAD:main
